name: todo_or_not_todo
description: "To do or not to do"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.7
  responsive_framework: ^1.4.0


  mobile:
    path: ./packages/presenter/mobile

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true


