name: desktop
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  intl: ^0.19.0
  flutter_gen: any
  go_router: ^13.2.1
  injectable: ^2.4.1
  get_it: ^7.6.7
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  provider: ^6.1.2
  logger: ^2.3.0
  formz: 0.7.0
  validated: ^2.0.0

  domain:
    path: ../../../domain

  data:
    path: ../../../data

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/app/
