name: domain
description: "A new Flutter project."
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1
  injectable: ^2.4.0
  get_it: ^7.6.7
  logging: ^1.2.0
  logging_appenders: ^1.2.0+1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.8
  freezed: ^2.4.7

